name: "CreativeItemControl"
version: "${version}-${buildNumber}"
main: "de.cubeside.itemcontrol.Main"
api-version: 1.20
commands:
        cicreload:
                usage: /cicreload
                description: Reload CreativeItemControl configuration.
                permission: creativeitemcontrol.reload
permissions:
        creativeitemcontrol.reload:
                description: Allows usage of the /cicreload command.
                default: op
        creativeitemcontrol.bypass:
                description: Grant access to items not in creative menus and items in blacklists.
                children:
                        creativeitemcontrol.blacklist.*: true
                default: op
